services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gmao
      POSTGRES_PASSWORD: gmao
      POSTGRES_DB: gmao
    ports:
      - "5432:5432"
    volumes:
      - gmao_pg:/var/lib/postgresql/data
volumes:
  gmao_pg:
